DeveloperGomaneh/src/java/JsfClass/OrderController.java
package JsfClass;

import Entity.Order;
import JsfClass.util.JsfUtil;
import JsfClass.util.PaginationHelper;
import Bean.OrderFacade;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@Named("orderController")
@SessionScoped
public class OrderController implements Serializable {

    private Order current;
    private DataModel items = null;
    @EJB
    private Bean.OrderFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public OrderController() {
    }

    public Order getSelected() {
        if (current == null) {
            current = new Order();
            selectedItemIndex = -1;
        }
        return current;
    }

    private OrderFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Order) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Order();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle5").getString("OrderCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle5").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Order) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle5").getString("OrderUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle5").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Order) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle5").getString("OrderDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle5").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public Order getOrder(java.lang.Integer id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = Order.class)
    public static class OrderControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            OrderController controller = (OrderController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "orderController");
            return controller.getOrder(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Order) {
                Order o = (Order) object;
                return getStringKey(o.getId());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Order.class.getName());
            }
        }

    }

}

DeveloperGomaneh/web/order/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle5.CreateOrderTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle5.CreateOrderLabel_id}" for="id" />
                    <h:inputText id="id" value="#{orderController.selected.id}" title="#{bundle5.CreateOrderTitle_id}" required="true" requiredMessage="#{bundle5.CreateOrderRequiredMessage_id}"/>
                    <h:outputLabel value="#{bundle5.CreateOrderLabel_name}" for="name" />
                    <h:inputText id="name" value="#{orderController.selected.name}" title="#{bundle5.CreateOrderTitle_name}" required="true" requiredMessage="#{bundle5.CreateOrderRequiredMessage_name}"/>
                    <h:outputLabel value="#{bundle5.CreateOrderLabel_mobile}" for="mobile" />
                    <h:inputText id="mobile" value="#{orderController.selected.mobile}" title="#{bundle5.CreateOrderTitle_mobile}" />
                    <h:outputLabel value="#{bundle5.CreateOrderLabel_phone}" for="phone" />
                    <h:inputText id="phone" value="#{orderController.selected.phone}" title="#{bundle5.CreateOrderTitle_phone}" required="true" requiredMessage="#{bundle5.CreateOrderRequiredMessage_phone}"/>
                    <h:outputLabel value="#{bundle5.CreateOrderLabel_desc}" for="desc" />
                    <h:inputText id="desc" value="#{orderController.selected.desc}" title="#{bundle5.CreateOrderTitle_desc}" required="true" requiredMessage="#{bundle5.CreateOrderRequiredMessage_desc}"/>
                    <h:outputLabel value="#{bundle5.CreateOrderLabel_email}" for="email" />
                    <h:inputText id="email" value="#{orderController.selected.email}" title="#{bundle5.CreateOrderTitle_email}" required="true" requiredMessage="#{bundle5.CreateOrderRequiredMessage_email}"/>
                    <h:outputLabel value="#{bundle5.CreateOrderLabel_personal}" for="personal" />
                    <h:inputText id="personal" value="#{orderController.selected.personal}" title="#{bundle5.CreateOrderTitle_personal}" required="true" requiredMessage="#{bundle5.CreateOrderRequiredMessage_personal}"/>
                    <h:outputLabel value="#{bundle5.CreateOrderLabel_createdAt}" for="createdAt" />
                    <h:inputText id="createdAt" value="#{orderController.selected.createdAt}" title="#{bundle5.CreateOrderTitle_createdAt}" required="true" requiredMessage="#{bundle5.CreateOrderRequiredMessage_createdAt}">
                        <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                    </h:inputText>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{orderController.create}" value="#{bundle5.CreateOrderSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{orderController.prepareList}" value="#{bundle5.CreateOrderShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle5.CreateOrderIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

DeveloperGomaneh/web/order/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle5.EditOrderTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle5.EditOrderLabel_id}" for="id" />
                    <h:inputText id="id" value="#{orderController.selected.id}" title="#{bundle5.EditOrderTitle_id}" required="true" requiredMessage="#{bundle5.EditOrderRequiredMessage_id}"/>
                    <h:outputLabel value="#{bundle5.EditOrderLabel_name}" for="name" />
                    <h:inputText id="name" value="#{orderController.selected.name}" title="#{bundle5.EditOrderTitle_name}" required="true" requiredMessage="#{bundle5.EditOrderRequiredMessage_name}"/>
                    <h:outputLabel value="#{bundle5.EditOrderLabel_mobile}" for="mobile" />
                    <h:inputText id="mobile" value="#{orderController.selected.mobile}" title="#{bundle5.EditOrderTitle_mobile}" />
                    <h:outputLabel value="#{bundle5.EditOrderLabel_phone}" for="phone" />
                    <h:inputText id="phone" value="#{orderController.selected.phone}" title="#{bundle5.EditOrderTitle_phone}" required="true" requiredMessage="#{bundle5.EditOrderRequiredMessage_phone}"/>
                    <h:outputLabel value="#{bundle5.EditOrderLabel_desc}" for="desc" />
                    <h:inputText id="desc" value="#{orderController.selected.desc}" title="#{bundle5.EditOrderTitle_desc}" required="true" requiredMessage="#{bundle5.EditOrderRequiredMessage_desc}"/>
                    <h:outputLabel value="#{bundle5.EditOrderLabel_email}" for="email" />
                    <h:inputText id="email" value="#{orderController.selected.email}" title="#{bundle5.EditOrderTitle_email}" required="true" requiredMessage="#{bundle5.EditOrderRequiredMessage_email}"/>
                    <h:outputLabel value="#{bundle5.EditOrderLabel_personal}" for="personal" />
                    <h:inputText id="personal" value="#{orderController.selected.personal}" title="#{bundle5.EditOrderTitle_personal}" required="true" requiredMessage="#{bundle5.EditOrderRequiredMessage_personal}"/>
                    <h:outputLabel value="#{bundle5.EditOrderLabel_createdAt}" for="createdAt" />
                    <h:inputText id="createdAt" value="#{orderController.selected.createdAt}" title="#{bundle5.EditOrderTitle_createdAt}" required="true" requiredMessage="#{bundle5.EditOrderRequiredMessage_createdAt}">
                        <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                    </h:inputText>
                </h:panelGrid>
                <h:commandLink action="#{orderController.update}" value="#{bundle5.EditOrderSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle5.EditOrderViewLink}"/>
                <br />
                <h:commandLink action="#{orderController.prepareList}" value="#{bundle5.EditOrderShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle5.EditOrderIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

DeveloperGomaneh/web/order/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle5.ListOrderTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle5.ListOrderEmpty}" rendered="#{orderController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{orderController.items.rowCount > 0}">
                    <h:outputText value="#{orderController.pagination.pageFirstItem + 1}..#{orderController.pagination.pageLastItem + 1}/#{orderController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{orderController.previous}" value="#{bundle5.Previous} #{orderController.pagination.pageSize}" rendered="#{orderController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{orderController.next}" value="#{bundle5.Next} #{orderController.pagination.pageSize}" rendered="#{orderController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{orderController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle5.ListOrderTitle_id}"/>
                            </f:facet>
                            <h:outputText value="#{item.id}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle5.ListOrderTitle_name}"/>
                            </f:facet>
                            <h:outputText value="#{item.name}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle5.ListOrderTitle_mobile}"/>
                            </f:facet>
                            <h:outputText value="#{item.mobile}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle5.ListOrderTitle_phone}"/>
                            </f:facet>
                            <h:outputText value="#{item.phone}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle5.ListOrderTitle_desc}"/>
                            </f:facet>
                            <h:outputText value="#{item.desc}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle5.ListOrderTitle_email}"/>
                            </f:facet>
                            <h:outputText value="#{item.email}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle5.ListOrderTitle_personal}"/>
                            </f:facet>
                            <h:outputText value="#{item.personal}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle5.ListOrderTitle_createdAt}"/>
                            </f:facet>
                            <h:outputText value="#{item.createdAt}">
                                <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                            </h:outputText>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{orderController.prepareView}" value="#{bundle5.ListOrderViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{orderController.prepareEdit}" value="#{bundle5.ListOrderEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{orderController.destroy}" value="#{bundle5.ListOrderDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{orderController.prepareCreate}" value="#{bundle5.ListOrderCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle5.ListOrderIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

DeveloperGomaneh/web/order/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle5.ViewOrderTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle5.ViewOrderLabel_id}"/>
                    <h:outputText value="#{orderController.selected.id}" title="#{bundle5.ViewOrderTitle_id}"/>
                    <h:outputText value="#{bundle5.ViewOrderLabel_name}"/>
                    <h:outputText value="#{orderController.selected.name}" title="#{bundle5.ViewOrderTitle_name}"/>
                    <h:outputText value="#{bundle5.ViewOrderLabel_mobile}"/>
                    <h:outputText value="#{orderController.selected.mobile}" title="#{bundle5.ViewOrderTitle_mobile}"/>
                    <h:outputText value="#{bundle5.ViewOrderLabel_phone}"/>
                    <h:outputText value="#{orderController.selected.phone}" title="#{bundle5.ViewOrderTitle_phone}"/>
                    <h:outputText value="#{bundle5.ViewOrderLabel_desc}"/>
                    <h:outputText value="#{orderController.selected.desc}" title="#{bundle5.ViewOrderTitle_desc}"/>
                    <h:outputText value="#{bundle5.ViewOrderLabel_email}"/>
                    <h:outputText value="#{orderController.selected.email}" title="#{bundle5.ViewOrderTitle_email}"/>
                    <h:outputText value="#{bundle5.ViewOrderLabel_personal}"/>
                    <h:outputText value="#{orderController.selected.personal}" title="#{bundle5.ViewOrderTitle_personal}"/>
                    <h:outputText value="#{bundle5.ViewOrderLabel_createdAt}"/>
                    <h:outputText value="#{orderController.selected.createdAt}" title="#{bundle5.ViewOrderTitle_createdAt}">
                        <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                    </h:outputText>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{orderController.destroyAndView}" value="#{bundle5.ViewOrderDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{bundle5.ViewOrderEditLink}"/>
                <br />
                <h:commandLink action="#{orderController.prepareCreate}" value="#{bundle5.ViewOrderCreateLink}" />
                <br />
                <h:commandLink action="#{orderController.prepareList}" value="#{bundle5.ViewOrderShowAllLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle5.ViewOrderIndexLink}"/>

            </h:form>
        </ui:define>
    </ui:composition>

</html>